### ISSUE TITLE
Inconsistent strategy parameters input UI

### ISSUE THREAD

**Issue by l29ah** [SebKuzminsky/pycam#67]
https://dump.bitcheese.net/files/zulekev/pycam-inconsistent.ogv

**Comment by sumpfralle** [comment]
Thank you for your report and the screen recording.

Other people encountering the same issue would have probably appreciated some words describing the situation. Videos are currently hard to index for search engines :(

How to reproduce:
* choose the processing strategy "slice removal"
* switch to another processing strategy
* switch back to "slice removal"
* seemingly randomly the parameters "direction" and "milling style" are both visible or both hidden when "slice removal" is selected

Expected behaviour:
* the parameters "direction" and "milling style" should always be visible after switching to the "slice removal" strategy

Or did I misunderstand a part of your bug report?

**Comment by l29ah** [comment]
Yes, it's correct, thank you. I had a hard time finding the proper words for the report.

**Comment by sumpfralle** [comment]
No problem.

Regarding the inconsistent behaviour: the model behind the GUI is changing at the moment. I will keep this bug report open as a reminder until that is finished.

**Comment by sumpfralle** [comment]
I cannot reproduce this with the master branch anymore. Thus it is probably fixed.
