### ISSUE TITLE
AttributeError: 'module' object has no attribute 'ToolpathSettings'

### ISSUE THREAD

**Issue by l29ah** [SebKuzminsky/pycam#72]
git master, cli won't work:
`pycam --boundary-mode=along --progress=bar --export-gcode=pycam-cli-test.ngc --tool-shape=cylindrical --tool-size=3 --tool-feedrate=1000 --process-path-direction=xy --process-path-strategy=contour-follow --process-step-down=2 --process-overlap-percent=40 --process-milling-style=climb --safety-height=3 --gcode-no-start-stop-spindle`
```
Traceback (most recent call last):
  File "/usr/lib/python-exec/python2.7/pycam", line 725, in <module>
    exit_code = execute(parser, opts, args, pycam)
  File "/usr/lib/python-exec/python2.7/pycam", line 311, in execute
    tps = pycam.Gui.Settings.ToolpathSettings()
AttributeError: 'module' object has no attribute 'ToolpathSettings'
```

**Comment by sumpfralle** [comment]
Yes, sadly the script still contained misleading references to the features that worked only up to v0.5.1.

Now I fixed the documentation of the scripts's parameters in order to stop this confusion.

You may want to take a look at the "yaml-flow" branch and the file "scripts/pycam-flow" if you are interested in the upcoming non-interactive usage model.
