### ISSUE TITLE
At least svg derived representations use sets of lines to represent arcs

### ISSUE THREAD

**Issue by zancas** [SebKuzminsky/pycam#82]

**Comment by sumpfralle** [comment]
Yes, currently 2D models use lines as their basic unit. The implemented model operations currently rely on this simplicity.

I can imagine, that arcs will be supported natively by pycam, if we switch somewhen to an external library for 2D operations, that can handle arcs.

Or maybe a configurable precision for pycam's conversion of circles/arcs to lines would be sufficient?

**Comment by sumpfralle** [comment]
Recently (f29c90a514828aaeb22d0d8167745fb652b8a591) I added native support for SVG files. Even with this direct import, the resulting items are still lines (even for arcs).
For the forseeable future I do not think, that we will change the internal handling of 2D elements in order to support non-line objects.
Thus I am closing this issue for now.
